### ISSUE TITLE
add function name to key generation of eWRT.util.cache

### ISSUE THREAD

**Issue by ffshr** [weblyzard/ewrt#14]
At the moment, the key for the Cache decorators is calculated based on the function arguments, but not the function name itself. I.e. if two functions have the same signature and input and share a cache directory (if using DiskCached), the cache can return cached results for the wrong function. 

Are there reasons, why this is not implemented?

**Comment by AlbertWeichselbraun** [comment]
Sharing cache directories has been discouraged so far. But I agree, that making these directories shareable would be very useful.
=> if you want to implement this feature - please go for it :smile:
