### ISSUE TITLE
get eWRT into pip

### ISSUE THREAD

**Issue by ffshr** [weblyzard/ewrt#9]
Since eWRT is publicly accessible and open source, we could get it into pip.

**Comment by amueller** [comment]
Any chance any of you is muncca on pypi? https://warehouse.python.org/user/muncca/ ? he owns your package and mine.

**Comment by AlbertWeichselbraun** [comment]
Muncca is not in our team, but I know him, since he has been a student of mine. I will ask him to contact you regarding your package.
(We had the same problem with eWRT where it took us some time to figure out who has published it on pip).

**Comment by amueller** [comment]
Thanks :)
